name = "DeepCFR"
uuid = "8c28a765-69da-4b11-9191-9a4a2c83148b"
authors = ["WhiffleFish <tylertronics@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CounterfactualRegret = "9fefe0b7-a0d5-4e12-a8ed-3472cccdfc49"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CounterfactualRegret = "0.2"
Flux = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
